[package]
name = "page_table_multiarch"
edition = "2021"
description = "Generic page table structures for various hardware architectures"
documentation = "https://docs.rs/page_table_multiarch"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
log = "0.4"
memory_addr = "0.2"
page_table_entry = { path = "../page_table_entry", version = "0.2" }
