[package]
name = "page_table_multiarch"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "Generic page table structures for various hardware architectures"
license = "GPL-3.0-or-later OR Apache-2.0 OR MulanPSL-2.0"
homepage = "https://github.com/arceos-org/arceos"
repository = "https://github.com/arceos-org/page_table_multiarch"
documentation = "https://docs.rs/page_table_multiarch"

[dependencies]
log = "0.4"
memory_addr = "0.1"
page_table_entry = { path = "../page_table_entry" }
