[package]
name = "page_table_entry"
edition = "2021"
description = "Page table entry definition for various hardware architectures"
documentation = "https://docs.rs/page_table_entry"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
bitflags = "2.6"
memory_addr = "0.2"
aarch64-cpu = "9.4" # TODO: put it in [target.'cfg(target_arch = "aarch64")'.dependencies]

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = "0.15"
